### ISSUE TITLE
Add avatar to the notification

### ISSUE THREAD

**Issue by ghost** [Eidenz/XSOverlay-BetterDiscord#1]
I hate doing feature requests but could you add the avatar of the user? 
You can use the URL size parameter to get a smaller version of it and pass it as base64 string to display in the notification, that's how it's done already on the Powercord version.

**Comment by Eidenz** [comment]
Yeah sounds good. I also need to replace the `[@user]` thingy with the actual username and support a few more things as well.

**Comment by ghost** [comment]
Would be great, besides that the plugin works well ♥️

**Comment by Eidenz** [comment]
Kinda forgot about the request, sorry.

Implemented the new features with 6b96de5
